---
- name: "Excalidraw stack"
  hosts: "cluster_managers[0]"
  become: true
  tasks:
    # +------------------------------------------+
    # |              PREREQUISITES               |
    # +------------------------------------------+

    - name: "Populate service facts"
      ansible.builtin.service_facts: {}
      tags: ["start", "stop"]

    - name: "Docker needs to be started"
      ansible.builtin.fail:
        msg: "Docker needs to be started"
      when: "'docker.service' not in ansible_facts.services"
      tags: ["start", "stop"]

    - name: "Docker needs to be running"
      ansible.builtin.fail:
        msg: "Docker needs to be started"
      when: "ansible_facts.services['docker.service'].state != 'running'"
      tags: ["start", "stop"]

    - name: "Check if the 'public' network exists"
      community.docker.docker_network_info:
        name: "public"
      register: "public_network"
      tags: ["start"]

    - name: "'public' network should exists"
      ansible.builtin.fail:
        msg: "'public' network is not present"
      when: "public_network.exists == false"
      tags: ["start"]

    # +------------------------------------------+
    # |                  START                   |
    # +------------------------------------------+

    - name: "Ensure that the stack is absent"
      community.docker.docker_stack:
        name: "excalidraw"
        state: "absent"
      tags: ["start"]

    - name: "Create the stack"
      community.docker.docker_stack:
        detach: true
        name: "excalidraw"
        state: "present"
        compose:
          - version: "3"
            services:
              excalidraw:
                image: "excalidraw/excalidraw:latest"
                networks: ["public"]
                deploy:
                  replicas: 1
                  mode: "replicated"
                  labels:
                    - "com.centurylinklabs.watchtower.enable=true"
                    - "traefik.enable=true"
                    - "traefik.http.routers.excalidraw.rule=Host(`draw.{{ domain }}`)"
                    - "traefik.http.routers.excalidraw.entrypoints=https"
                    - "traefik.http.routers.excalidraw.middlewares=authelia@file"
                    - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
                    - "homepage.name=Excalidraw"
                    - "homepage.group=Services"
                    - "homepage.icon=sh-excalidraw"
                    - "homepage.description=C̶o̶l̶l̶a̶b̶o̶r̶a̶t̶i̶v̶e whiteboard."
                    - "homepage.href=https://draw.{{ domain }}"
            networks:
              public: { external: true }
      tags: ["start"]

    # +------------------------------------------+
    # |                   STOP                   |
    # +------------------------------------------+

    - name: "Remove the service"
      community.docker.docker_stack:
        name: "excalidraw"
        state: "absent"
      tags: ["stop"]
...
