# ** This is a template file. Copy it and rename it to `inventory.yml`

# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/inventory.json
---
nfs:
  hosts:
    192.168.1.253: {}

cluster_managers:
  hosts:
    192.168.1.2: {}
    192.168.1.3: {}
    192.168.1.4: {}

cluster_workers:
  hosts: {}

cluster:
  children:
    cluster_managers: {}
    cluster_workers: {}
  vars:
    domain: ""
    banner: ""
    tz: ""
    admin:
      password: ""
    apikeys:
      duckdns: ""
    secret: ""  # openssl rand -base64 32
    acme:
      email: ""
      provider: ""
      tokens:
        CF_DNS_API_TOKEN: ""
...
